spring.application.name=auth-service
server.port=8001

# -----------------------------------------------------
# CONFIGURACIÓN PARA SUPABASE (POSTGRESQL)
# -----------------------------------------------------

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------------------------------
# JPA & HIBERNATE (Reglas de las tablas)
# -----------------------------------------------------


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Especificamos el esquema 'usuarios' para organizar nuestras tablas
spring.jpa.properties.hibernate.default_schema=usuarios

#'create-drop' por 'update'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT Configuration
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration=3600000

##DOCKER HEALTH CHECK
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

##deshabilitar la configuración de seguridad automática de Spring Boot para evitar conflictos con nuestra configuración personalizada
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Limita las conexiones máximas de Hikari a 2 o 3
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1