spring.application.name=auth-service

# Configuración para desarrollo con H2 (base de datos en memoria)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (opcional, para ver la DB en navegador)
spring.h2.console.enabled=true

server.port=8080

jwt.secret=MiClaveSuperSecretaParaJWT123456789
jwt.expiration=3600000
