spring.application.name=auth-service

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: postgres
    password: tu_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: MiClaveSuperSecretaParaJWT123456789
  expiration: 3600000  # 1 hora en milisegundos
