# Imagen oficial de PostgreSQL
FROM postgres:16

# Variables de entorno para inicializar la base de datos
ENV POSTGRES_DB=authdb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=tu_password

# Exponer puerto PostgreSQL
EXPOSE 5432