name: Build and Push Auth Service to GHCR

on:
  push:
    branches:
      - Develop-Max # Cambia a 'main' si tu rama principal se llama así

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }} # Usamos el secreto que ya creaste

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./auth-service
          # IMPORTANTE: Si el Dockerfile está dentro de la carpeta 'auth-service', 
          # cambia el context a: ./auth-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}